# Generated by Django 5.2.3 on 2025-06-24 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=50, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('allocated', 'Allocated'), ('retired', 'Retired'), ('under repair', 'Under Repair')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('employee_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract'), ('Intern', 'Intern')], max_length=10)),
                ('date_of_joining', models.DateField()),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AllocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('New', 'New'), ('Return', 'Return'), ('Replace', 'Replace'), ('Repair', 'Repair'), ('Additional', 'Additional')], max_length=10)),
                ('status', models.CharField(choices=[('Allocated', 'Allocated'), ('Returned', 'Returned'), ('In Repair', 'In Repair')], max_length=15)),
                ('reason', models.TextField()),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.asset')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('New', 'New'), ('Return', 'Return'), ('Replace', 'Replace'), ('Repair', 'Repair'), ('Additional', 'Additional')], max_length=10)),
                ('status', models.CharField(choices=[('Allocated', 'Allocated'), ('Returned', 'Returned'), ('In Repair', 'In Repair')], max_length=15)),
                ('reason', models.TextField()),
                ('assigned_date', models.DateField()),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.asset')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.employee')),
            ],
        ),
    ]
