# Generated by Django 5.2.3 on 2025-10-28 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(default='Laptop', max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('processor', models.CharField(blank=True, max_length=255, null=True)),
                ('ram_gb', models.IntegerField(blank=True, null=True)),
                ('storage_size_gb', models.IntegerField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Available', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory_asset',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(help_text='Must be a unique email address.', max_length=255, unique=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_employee',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('allocation_id', models.AutoField(primary_key=True, serialize=False)),
                ('it_spoc_employee_id', models.IntegerField(blank=True, help_text='ID of the IT admin handling the transaction.', null=True)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('allocation_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_condition_on_alloc', models.CharField(blank=True, max_length=255, null=True)),
                ('charger_status', models.CharField(blank=True, max_length=50, null=True)),
                ('bag_status', models.CharField(blank=True, max_length=50, null=True)),
                ('keyboard_and_touchpad_status', models.CharField(blank=True, max_length=50, null=True)),
                ('allocation_location', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_type', models.CharField(blank=True, max_length=50, null=True)),
                ('allocation_docket_id', models.CharField(blank=True, max_length=100, null=True)),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
                ('return_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_power_status', models.CharField(blank=True, max_length=50, null=True)),
                ('asset_screen_status', models.CharField(blank=True, max_length=50, null=True)),
                ('charger_return_status', models.CharField(blank=True, max_length=50, null=True)),
                ('bag_return_status', models.CharField(blank=True, max_length=50, null=True)),
                ('return_location', models.CharField(blank=True, max_length=255, null=True)),
                ('return_docket_id', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('transaction_status', models.CharField(default='Allocated', max_length=50)),
                ('asset', models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='inventory.asset')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='inventory.employee')),
            ],
            options={
                'db_table': 'inventory_allocation',
                'ordering': ['-assigned_date'],
            },
        ),
    ]
